p8105_hw2_jm5509
================
Echo
2022-09-28

## Problem 1

``` r
nyc_df <- read_csv('NYC_Transit_Subway_Entrance_And_Exit_Data.csv',
                   col_types=cols(
                     `Route8`=col_character(),
                     `Route9`=col_character(),
                     `Route10`=col_character(),
                     `Route11`=col_character(),
                   )) %>% 
  janitor::clean_names() %>% 
  select(line,station_name,station_latitude,station_longitude,
         starts_with('route'),entry, exit_only, vending, entrance_type, ada) %>% 
  mutate(entry=recode(entry, 'YES'=TRUE,'NO'=FALSE))

nyc_df
```

    ## # A tibble: 1,868 × 20
    ##    line     station_…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6
    ##    <chr>    <chr>        <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  2 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  3 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  4 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  5 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  6 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  7 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  8 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  9 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 10 4 Avenue 53rd St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 1,858 more rows, 10 more variables: route7 <chr>, route8 <chr>,
    ## #   route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>, exit_only <chr>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>, and abbreviated variable
    ## #   names ¹​station_name, ²​station_latitude, ³​station_longitude

This is the first step of data management——reading and cleaning the
data. This nyc transit data include the information of the nyc subway
station names, the entries and exits, the location of the stations, the
route that go pass the station, and the vending facilities. I clean the
data by setting some of the numeric variables(route8:11) as character
variables, and clean all of the variables names as the combination of
lower-case letters and underscores. Then I select some of the variables
I would probably use later, and change the value of “entry” variable
from “YES”/“NO” into the logical value of TRUE/FALSE.

**However, these data are still not tidy now.** These route1 to route11
variables spread across columns, which correspond to four observation
times. We can do the data-tidy job steo by step while answering the
following questions.

**How many distinct stations are there?** To get the information of the
stations, we need to get the distinct station data.

``` r
(nyc_df_distinct_station <- nyc_df%>% 
  distinct(line,station_name,.keep_all = TRUE))
```

    ## # A tibble: 465 × 20
    ##    line     station_…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6
    ##    <chr>    <chr>        <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  2 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  3 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  4 4 Avenue 53rd St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  5 4 Avenue 59th St       40.6   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  6 4 Avenue 77th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  7 4 Avenue 86th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  8 4 Avenue 95th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  9 4 Avenue 9th St        40.7   -74.0 F      G      R      <NA>   <NA>   <NA>  
    ## 10 4 Avenue Atlantic …    40.7   -74.0 B      Q      D      N      R      2     
    ## # … with 455 more rows, 10 more variables: route7 <chr>, route8 <chr>,
    ## #   route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>, exit_only <chr>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>, and abbreviated variable
    ## #   names ¹​station_name, ²​station_latitude, ³​station_longitude

``` r
nrow(nyc_df_distinct_station)
```

    ## [1] 465

Identified by line and station name, we know that **465** stations are
distinct.

**How many stations are ADA compliant?**

``` r
(nyc_df_distinct_station %>% filter(ada==TRUE) %>% nrow())
```

    ## [1] 84

Of all the distinct stations, **84** stations are ADA-compliant.

**What proportion of station entrances / exits without vending allow
entrance?**

``` r
(entry_count <- nyc_df %>% 
  select(line,station_name,entry,vending) %>% 
  filter(vending=='NO',entry==TRUE) %>% 
  nrow())
```

    ## [1] 69

``` r
(novending_count <- nyc_df %>% 
 select(line,station_name,entry,vending) %>% 
  filter(vending=='NO') %>% 
  nrow())
```

    ## [1] 183

``` r
(proportion <- entry_count/novending_count)
```

    ## [1] 0.3770492

**37.7%** of station entrances / exits without vending allow entrance.
There are 183 entrances / exits without vending, and 69 of these allow
entry.

Here, before answering the next question, we can fix the route variable
problem talked about before by using the pivot_longer().

``` r
(nyc_df_reformat <-  nyc_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_name", 
    values_to = "route_number"))
```

    ## # A tibble: 20,548 × 11
    ##    line     statio…¹ stati…² stati…³ entry exit_…⁴ vending entra…⁵ ada   route…⁶
    ##    <chr>    <chr>      <dbl>   <dbl> <lgl> <chr>   <chr>   <chr>   <lgl> <chr>  
    ##  1 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route1 
    ##  2 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route2 
    ##  3 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route3 
    ##  4 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route4 
    ##  5 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route5 
    ##  6 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route6 
    ##  7 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route7 
    ##  8 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route8 
    ##  9 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route9 
    ## 10 4 Avenue 25th St     40.7   -74.0 TRUE  <NA>    YES     Stair   FALSE route10
    ## # … with 20,538 more rows, 1 more variable: route_number <chr>, and abbreviated
    ## #   variable names ¹​station_name, ²​station_latitude, ³​station_longitude,
    ## #   ⁴​exit_only, ⁵​entrance_type, ⁶​route_name

In this case, the route number and route name are distinct variables. We
can continue working on the following questions.

**How many distinct stations serve the A train?**

``` r
(A_count <- nyc_df_reformat %>% 
  filter(route_number=='A') %>% 
  distinct(line,station_name,.keep_all = TRUE) %>% 
  nrow())
```

    ## [1] 60

**60** is the number of the stations that serve the A train.

**Of the stations that serve the A train, how many are ADA compliant?**

``` r
A_ADAcompliant_count <-nyc_df_reformat %>% 
  filter(route_number=='A',ada==TRUE) %>% 
  distinct(line,station_name,.keep_all = TRUE) %>% 
  nrow() 
```

**17** is the number of the ADA-compliant stations that serve the A
train.

## Problem 2

This problem is about reading and tidying trash data. First I will read
the corresponding sheet of the excel file, and then omit the rows and
columns that do not contain the trash data. Furthermore, I will rename
the first column and filter the rows that contain NA and the total
number. In the end, I will round the number of sports balls to the
nearest integer and converts the result to an integer variable.

``` r
mrtrash_df <- read_excel('Trash-Wheel-Collection-Totals-7-2020-2.xlsx',
                            sheet = 'Mr. Trash Wheel', range = cell_cols('A:N'),
                            skip = 1) %>% 
  janitor::clean_names() %>% 
  rename(dump_num = dumpster) %>% 
  filter(!(is.na(dump_num) | dump_num == 'Grand Total')) %>% 
  mutate(sports_balls= as.integer(round(sports_balls, 0)))

mrtrash_df
```

    ## # A tibble: 453 × 14
    ##    dump_num month  year date                weight_tons volume…¹ plast…² polys…³
    ##    <chr>    <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1 1        May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2 2        May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3 3        May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4 4        May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5 5        May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6 6        May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7 7        May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8 8        May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9 9        June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10 10       June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 443 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

``` r
colnames(mrtrash_df)
```

    ##  [1] "dump_num"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "glass_bottles"      "grocery_bags"       "chip_bags"         
    ## [13] "sports_balls"       "homes_powered"

This produces a tibble of **453 observations** and **14 variables**. The
key variables include *dump_num*, *year*, *weight_tons*,
*sports_balls*,etc.

The reading and cleaning steps of Professor Trash Wheel sheet are the
same.

``` r
proftrash_df <- read_excel('Trash Wheel Collection Data.xlsx',
                            sheet = 'Professor Trash Wheel', 
                           range = cell_cols('A:N'), skip = 1) %>% 
  janitor::clean_names() %>% 
  rename(dump_num = dumpster) %>% 
  filter(!(is.na(dump_num) | dump_num == 'Grand Total')) 
```

    ## New names:
    ## • `` -> `...14`

``` r
proftrash_df
```

    ## # A tibble: 94 × 14
    ##    dump_num month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2        2 January   2017 2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3        3 February  2017 2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4        4 February  2017 2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5        5 February  2017 2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6        6 March     2017 2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7        7 April     2017 2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8        8 April     2017 2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9        9 May       2017 2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10       10 May       2017 2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 84 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, x14 <lgl>, and abbreviated variable names
    ## #   ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles, ⁴​polystyrene

This produces a tibble of **94 observations** and **14 variables**.The
key variables include *dump_num*, *year*, *weight_tons*, etc.

After getting these 2 datasets, we can join them into 1 tidy dataset.
But first, we can add an additional variable to both datasets before
combining to keep track of which Trash Wheel is which.

``` r
proftrash_df <- proftrash_df %>% 
mutate(label=rep('prof_trash',nrow(proftrash_df)))

proftrash_df
```

    ## # A tibble: 94 × 15
    ##    dump_num month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2        2 January   2017 2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3        3 February  2017 2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4        4 February  2017 2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5        5 February  2017 2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6        6 March     2017 2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7        7 April     2017 2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8        8 April     2017 2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9        9 May       2017 2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10       10 May       2017 2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 84 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, x14 <lgl>, label <chr>, and abbreviated variable names
    ## #   ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles, ⁴​polystyrene

``` r
mrtrash_df <- mrtrash_df %>% 
mutate(label=rep('mr_trash',nrow(mrtrash_df))) %>% 
   mutate(dump_num = as.double(dump_num))

mrtrash_df
```

    ## # A tibble: 453 × 15
    ##    dump_num month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 443 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, label <chr>, and abbreviated
    ## #   variable names ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

The next step is dataset combination. I would use the function of
full_join() to keep all the data of these 2 datasets, and join them by
their shared variables.

``` r
(alltrash_df <- full_join(mrtrash_df,proftrash_df, 
                         by = intersect(colnames(mrtrash_df),
                                        colnames(proftrash_df))))
```

    ## # A tibble: 547 × 16
    ##    dump_num month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 537 more rows, 8 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, label <chr>, x14 <lgl>, and
    ## #   abbreviated variable names ¹​volume_cubic_yards, ²​plastic_bottles,
    ## #   ³​polystyrene

In this way, I get a tibble of **547 observations** and **16
variables**. The key variables include *dump_num*, *year*,
*weight_tons*, *sports_balls*,etc.

The illustrate the information of the datasets,better, we can extract
some of the info we want. For example, the 2 following questions could
help:

**What was the total weight of trash collected by Professor Trash
Wheel?** **What was the total number of sports balls collected by
Mr.Trash Wheel in 2020?**

``` r
sum(proftrash_df$weight_tons)
```

    ## [1] 190.12

``` r
(mrtrash2020_df <- mrtrash_df %>% filter(year == 2020))
```

    ## # A tibble: 72 × 15
    ##    dump_num month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1      381 January   2020 2020-01-18 00:00:00      2.75      15    3900    2100
    ##  2      382 January   2020 2020-01-18 00:00:00      1.8       15    2900    1800
    ##  3      383 January   2020 1900-01-20 00:00:00      2.9       15    1850    1100
    ##  4      384 January   2020 2020-01-27 00:00:00      2.54      15    3400    2400
    ##  5      385 January   2020 2020-01-27 00:00:00      2.18      15     980     900
    ##  6      386 January   2020 2020-01-27 00:00:00      3.24      15     750     640
    ##  7      387 January   2020 2020-01-27 00:00:00      3.07      15     500     440
    ##  8      388 January   2020 2020-01-30 00:00:00      2.8       15    3200    2400
    ##  9      389 January   2020 2020-01-30 00:00:00      2.8       15    3800    2700
    ## 10      390 February  2020 2020-02-10 00:00:00      1.9       15    1850     980
    ## # … with 62 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, label <chr>, and abbreviated
    ## #   variable names ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles,
    ## #   ⁴​polystyrene

``` r
sum(mrtrash2020_df$sports_balls)
```

    ## [1] 856

The total weight of trash collected by Professor Trash Wheel is **190.12
tons**. The total number of sports balls collected by Mr. Trash Wheel in
2020 is **856**.

## Problem 3

This problem uses the FiveThirtyEight data. We’ll use the data in
pols-month.csv, unemployment.csv, and snp.csv. Our goal is to merge
these into a single data frame using year and month as keys across
datasets.

First step is to read and clean the pols-month datasets. We use
separate() to break up the variable mon into integer variables year,
month, and day; replace month number with month name; create a president
variable taking values gop and dem, and remove prez_dem and prez_gop;
and remove the day variable.

``` r
(pols_df <- read_csv('fivethirtyeight_datasets/pols-month.csv') %>% 
  separate(mon, into = c('year','month','day'),sep = '-') %>% 
  mutate(year = as.integer(year), month = as.integer(month),
         day=as.integer(day)) %>% 
  mutate(month = month.abb[month]) %>% 
  mutate(president = ifelse(prez_gop == 1, 'gop', 'dem')) %>% 
  select(- c(day, prez_gop, prez_dem)))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## # A tibble: 822 × 9
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 Jan        23      51     253      23      45     198 dem      
    ##  2  1947 Feb        23      51     253      23      45     198 dem      
    ##  3  1947 Mar        23      51     253      23      45     198 dem      
    ##  4  1947 Apr        23      51     253      23      45     198 dem      
    ##  5  1947 May        23      51     253      23      45     198 dem      
    ##  6  1947 Jun        23      51     253      23      45     198 dem      
    ##  7  1947 Jul        23      51     253      23      45     198 dem      
    ##  8  1947 Aug        23      51     253      23      45     198 dem      
    ##  9  1947 Sep        23      51     253      23      45     198 dem      
    ## 10  1947 Oct        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

This produces a tibble of **822 observations** and **9 variables**. The
year ranges from 1950 to 2015. It includes year-month, gov_gop(the
number of republican governors on the associated date), sen_gop(the
number of republican senators on the associated date), rep_gop(number of
republican representatives on the associated date), gov_dem(the number
of democratic governors on the associated date), sen_dem(the number of
democratic senators on the associated date), rep_dem(the number of
democratic representatives on the associated date),president(the
president was democratic or republican on the associated date) .

Second, clean the data in snp.csv using a similar process to the above.
For consistency across datasets, we arrange according to year and month,
and organize so that year and month are the leading columns. This
dataset is kinda trick to deal with, because Note that again for
consistency again datasets, we will replace month number with month
name.

``` r
(snp_df <- read_csv('fivethirtyeight_datasets/snp.csv')  %>% 
  separate(date, into = c('month','day','year'),sep = '/') %>%
  mutate(year = as.numeric(year)) %>%  
  mutate(year = ifelse(year<= 15, year + 2000, year + 1900)) %>% 
  mutate(month = as.numeric(month), day = as.numeric(day)) %>%
  arrange(year, month) %>% 
  mutate(month = month.abb[month]) 
)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## # A tibble: 787 × 4
    ##    month   day  year close
    ##    <chr> <dbl> <dbl> <dbl>
    ##  1 Jan       3  1950  17.0
    ##  2 Feb       1  1950  17.2
    ##  3 Mar       1  1950  17.3
    ##  4 Apr       3  1950  18.0
    ##  5 May       1  1950  18.8
    ##  6 Jun       1  1950  17.7
    ##  7 Jul       3  1950  17.8
    ##  8 Aug       1  1950  18.4
    ##  9 Sep       1  1950  19.5
    ## 10 Oct       2  1950  19.5
    ## # … with 777 more rows

This produces a tibble of **787 observations** and **4 variables**. It
includes *year*,*month*,*day*,and *close* (closing values of the S&P
stock index on the associated date).

Third, we will tidy the unemployment data so that it can be merged with
the previous datasets. This process will involve switching from “wide”
to “long” format; ensuring that key variables have the same name; and
ensuring that key variables take the same values.

``` r
(unem_df <- read_csv('fivethirtyeight_datasets/unemployment.csv') %>% 
 pivot_longer(Jan:Dec, names_to = 'month', values_to = 'unemployed_rate') %>% 
  janitor::clean_names())
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## # A tibble: 816 × 3
    ##     year month unemployed_rate
    ##    <dbl> <chr>           <dbl>
    ##  1  1948 Jan               3.4
    ##  2  1948 Feb               3.8
    ##  3  1948 Mar               4  
    ##  4  1948 Apr               3.9
    ##  5  1948 May               3.5
    ##  6  1948 Jun               3.6
    ##  7  1948 Jul               3.6
    ##  8  1948 Aug               3.9
    ##  9  1948 Sep               3.8
    ## 10  1948 Oct               3.7
    ## # … with 806 more rows

This produces a tibble of **816 observations** and **3 variables**. It
includes *year*, *month*,and the corresponding *unemployment percentage*
on that date.

Last, we will join the datasets by merging snp into pols, and merging
unemployment into the result by using the function left_join().

``` r
(result_df <- left_join(pols_df, snp_df, by = c('year', 'month')))
```

    ## # A tibble: 822 × 11
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president   day
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem          NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem          NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem          NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem          NA
    ##  5  1947 May        23      51     253      23      45     198 dem          NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem          NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem          NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem          NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem          NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem          NA
    ## # … with 812 more rows, and 1 more variable: close <dbl>

``` r
(final_result_df <- left_join(result_df, unem_df, by = c('year', 'month')))
```

    ## # A tibble: 822 × 12
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president   day
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem          NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem          NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem          NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem          NA
    ##  5  1947 May        23      51     253      23      45     198 dem          NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem          NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem          NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem          NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem          NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem          NA
    ## # … with 812 more rows, and 2 more variables: close <dbl>,
    ## #   unemployed_rate <dbl>

The *result_df* is a tibble of **822 observations** and **11
variables**, and the *final_result_df* is a tibble of **822
observations** and **11 variables**. Key variables of final result
include year-month-day, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem,
rep_dem, president, close, unemployment_rate.
